### ISSUE TITLE
bind value formatting as per given dateFormat

### ISSUE THREAD

**Issue by rvanderfeer** [jacobmischka/svelte-flatpickr#17] opened 2020-01-28 13:45 UTC
I was expecting the bound variable to be formatted as per the dateFormat spec.

instead of the current implementation;
```
function updateValue(newValue) {
	value = (Array.isArray(newValue) && newValue.length === 1) ? newValue[0] : newValue;
}
```

I was expecting something along these lines;
```
function updateValue(newValue) {
	newValue = newValue.map((e) => fp.formatDate(new Date(e), dateFormat));
	value = (Array.isArray(newValue) && newValue.length === 1) ? newValue[0] : newValue;
}
```

This may be by design or I may have missed the proper way to achieve this, could you elaborate?

**Comment by jacobmischka** [comment] 2020-01-28 13:56
This is by design, though I suppose the design could be worth reconsidering. I wanted the `value` to represent the actual Date value(s), not the formatted strings.

As per the [flatpickr documentation of events](https://flatpickr.js.org/events/), each hook receives 3 arguments, the second of which is the formatted date string. All this funky function does is strip the array wrapper if there's only one selected date as a convenience.

If you want the formatted date string, you can add your own hook via the options object like this:

```js
<Flatpickr options={{
  onChange(dates, dateStr) { console.log(dateStr); }
}} />
```

**Comment by rvanderfeer** [comment] 2020-01-28 16:31
I tried using the onChange handler but that causes inconvenience in my use case as I have many date and time fields together forming a schedule table of sorts and there didn't seem to be an elegant way to somehow overwrite the bound variable.
I think I would need to provide the variable/property name on a per-use basis - is that correct?

In my use case the value is bound to an object property (a model representation) which is initially a string formatted Y-m-d, eg. '2020-01-28'.

For me changing the type from String to Date causes problems as I'm serialising the model to JSON and this will not only have a different format, but also change a simple date to a complete datetime with timezone ('2020-01-28' becomes '2020-01-27T23:00:00.000Z').

The same will occur on a different model that just has a time property formatted 'H:i' ('01:00' becomes '2020-01-28T00:00:00.000Z').

The fact that localisation now comes into play for a simple time was confusing for me; mostly because my time property will never have a date component as it is something independent
of date; it is a part of a schedule (eg. daily from 10:00 until 11:00) but also the fact that I am not on standard time and now need to convert back to GMT+1.

From my perspective having a choice what you're binding to would be beneficial, binding to the date object like per design could be just as much of a use case, I can imagine, but the type of the variable changing seems quite dangerous to me.
Perhaps adding a 'formattedValue' prop to bind to could allow both use cases to co-exist?

**Comment by jacobmischka** [comment] 2020-01-29 22:21
> Perhaps adding a 'formattedValue' prop to bind to could allow both use cases to co-exist?

Great idea!

**Comment by jacobmischka** [comment] 2020-01-29 22:28
Released in `2.4.0`!

**Closed by jacobmischka** 2020-01-29 22:28 UTC

**Comment by rvanderfeer** [comment] 2020-01-30 10:49
👍  You beat me to it

May I suggest changing;
```
$: if (fp) fp.setDate(value, false, dateFormat);
```

To:
```
$: if (fp) fp.setDate(value?value:formattedValue, false, dateFormat);
```

It should allow for supplying only the formattedValue prop I think.

Sorry for the mangled process, I'll create a PR next time.

**Comment by jacobmischka** [comment] 2020-01-30 14:48
I don't think that would work how you expect, since even if `value` isn't being provided from the parent it's still being set in the change handler. So no matter what `value` won't be empty after an update.

PR welcome for a better solution though!
