### ISSUE TITLE
How to use with Sapper and SSR?

### ISSUE THREAD

**Issue by PaulMaly** [jacobmischka/svelte-flatpickr#8] opened 2019-04-26 17:46 UTC
Hi! I try to use in Sapper app and get this message:

> <Flatpickr> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules

Are any options to use this great component with Sapper and SSR?

**Comment by jacobmischka** [comment] 2019-04-26 18:17
I believe it's because flatpickr itself references `window`. While I'd love to support this directly in this component if we can find a clean way, you should be able to workaround the issue using the dynamic import method detailed in the Sapper docs here: https://sapper.svelte.technology/guide#making-a-component-ssr-compatible

**Comment by PaulMaly** [comment] 2019-04-27 11:57
As I can see, you initialize `flatpickr` only inside `onMount` hook which shouldn't work on the server, I guess. So, basically, this is the correct way to implement browser-specific things inside the components. 

I'm not sure the problem in this, because yesterday I created simple `flatpickr action` and it's work perfectly with SSR, because `actions` are also not running on the server.

Should I close this issue or you're interested to provide SSR support for this component?

**Comment by jacobmischka** [comment] 2019-04-27 14:32
I'm interested! I think you're right, I can probably switch to using a dynamic import in `onMount`. I'll take a look soon!

**Comment by jacobmischka** [comment] 2019-04-30 14:44
Okay actually, I think the dynamic import isn't required, it looks like svelte-loader and rollup-plugin-svelte just aren't respecting the `svelte` field in this component's `package.json`. I have no idea why.

An explicit `import 'svelte-flatpickr/src/Flatpickr.svelte'` seems to work until this gets figured out.

**Comment by jacobmischka** [comment] 2019-04-30 15:33
Okay, I believe it _should_ work if `svelte-flatpickr` is specified as a `devDependency` instead of a dependency, assuming you're using the default sapper template. I think this all boils down to loader configuration and there isn't anything that can be changed in this package. I've run into this problem myself in the past, and I had no idea that this was the cause. If this doesn't seem to be the cause of your issue please write back.

https://github.com/sveltejs/sapper-template#using-external-components-with-webpack

**Comment by jacobmischka** [comment] 2019-05-07 19:01
I'm gonna close this because I think it's fundamentally a usage configuration issue and not anything I can do in this library. Feel free to write back if I'm mistaken!

**Closed by jacobmischka** 2019-05-07 19:01 UTC
